apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "api.name" . }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ printf "fr-%s-mpf" .Values.env }}
  data:
  - key: {{ printf "%s01-%s-postgres-username-mpf" .Values.env .Values.region }}
    name: rdb_user
    version: latest
    property: value
  - key: {{ printf "%s01-%s-postgres-password-mpf" .Values.env .Values.region }}
    name: rdb_password
    version: latest
    property: value
  - key: {{ printf "%s01-%s-azure-ad-client-secret" .Values.env .Values.region }}
    name: azure_ad_client_secret
    version: latest
    property: value