apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.service.name" . }}
  labels:
    {{- include "api.commonLabels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: {{ printf "{\"ports\": {\"http\":%s}}" (include "api.backend.name" . | quote ) | squote }}
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
spec: # Service's specification
  type: ClusterIP
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port:  {{ .Values.port.service }}
    protocol: TCP
    targetPort: {{ .Values.port.target }}