# Determines whether the Helm chart or kubernetes-external-secrets
# will handle the ExternalSecret CRD
customResourceManagerDisabled: false

crds:
  # only needed for helm v2, leave this disabled for helm v3
  create: false

# Environment variables to set on deployment pod
env:
  POLLER_INTERVAL_MILLISECONDS: 10000
  WATCH_TIMEOUT: 60000
  WATCHED_NAMESPACES: ''
  LOG_LEVEL: info
  LOG_MESSAGE_KEY: 'msg'
  METRICS_PORT: 3001

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Specifies annotations for this service account
  annotations:
    iam.gke.io/gcp-service-account: prd01-mpf-api@fr-prd-mpf.iam.gserviceaccount.com
  # require editing
  name: external-secret-sa

replicaCount: 1

image:
  repository: ghcr.io/external-secrets/kubernetes-external-secrets
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

priorityClassName: ""

dnsConfig: {}
securityContext:
  runAsNonRoot: true
  # Required for use of IRSA, see https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
  # fsGroup: 65534

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podDisruptionBudget: {}

serviceMonitor:
  enabled: false
  interval: "30s"
  namespace:
  deploymentInitContainers: {}

extraVolumes: []
  # - name: namedVolume
  # emptyDir: {}

extraVolumeMounts: []
# - name: namedVolume
# mountPath: /usr/path
# readOnly: false

# Add additional RBAC rules to the ClusterRole granted to the service account
customClusterRoles: {}